### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by stqism** [ToxMe/toxme.se#1]
- [X] Make resolvable when server down
- [x] Distributed database (wip, Postgres)
- [ ] Email support (backend done, working on ui (email sean@toxme.se))
- [ ] Tox ID based recovery (bot or a tool)
